flatt_design/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views, settings

urlpatterns = [
    url(r'^posts/', include('posts.urls', namespace='posts')),
	url(r'^portfolio/', include('projects.urls', namespace='projects')),
    url(r'^services/$', views.services, name='services'),
    url(r'^team/$', views.team, name='team'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
]

if settings.DEBUG:
    urlpatterns += url(r'^media/(?P<path>.*)$', serve, {
                        'document_root': settings.MEDIA_ROOT,
                    }),

urlpatterns += staticfiles_urlpatterns()

posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.posts_index, name='index'),
	url(r'(?P<pk>\d+)/$', views.post_detail, name='detail'),
	url(r'(?P<tag>[\w-]+)/$', views.posts_category, name='category')
]

templates/contact.html
{% extends "layout/base.html" %}
{% load static from staticfiles %}

{% block title %}Contact Us{% endblock title %}

{% block cssextra %}
{% endblock cssextra %}

{% block content %}
	<!-- ============================================================= MAIN ============================================================= -->
		
	<main>
		
		<!-- ============================================================= SECTION – HERO ============================================================= -->
		
		<section id="hero" class="light-bg img-bg img-bg-softer" style="background-image: url({% static 'images/art/image-background04.jpg' %});">
			<div class="container inner">
				<div class="row">
					<div class="col-md-8">
						<header>
							<h1>Get in touch</h1>
							<p>Do you want to know more? We’d love to hear from you!</p>
						</header>
					</div><!-- /.col -->
				</div><!-- ./row -->
			</div><!-- /.container -->
		</section>
		
		<!-- ============================================================= SECTION – HERO : END ============================================================= -->
		
		<div class="container inner">
			<div class="row">
				
				<div class="col-md-8 inner-right-md">
					
					<!-- ============================================================= SECTION – CONTACT FORM ============================================================= -->
					{% if messages %}
					<div class="row">
						<div class="col-sm-12">
							{% for message in messages %}
								<div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
									<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
									{{ message }}
								</div>
							{% endfor %}
						</div>
					</div>
					{% endif %}
					<section id="contact-form2">
						<h2>Leave a Message</h2>
						<form action="" method="POST" class="forms">
							{{ form }}
							{% csrf_token %}
							<button type="submit" class="btn btn-default btn-submit">Send</button>
						</form>
					</section>
					
					<!-- <section id="contact-form">
						
						<h2>Leave a Message</h2>
						
						<form id="contactform" class="forms" action="contact.php" method="post">
							
							<div class="row">
								<div class="col-sm-6">
									<input type="text" name="name" class="form-control" placeholder="Name (Required)">
								</div>
							</div>
							
							<div class="row">
								<div class="col-sm-6">
									<input type="email" name="email" class="form-control" placeholder="Email (Required)">
								</div>
							</div>
							
							<div class="row">
								<div class="col-sm-6">
									<input type="text" name="subject" class="form-control" placeholder="Subject">
								</div>
							</div>
							
							<div class="row">
								<div class="col-sm-12">
									<textarea name="message" class="form-control" placeholder="Enter your message ..."></textarea>
								</div>
							</div>
							
							<button type="submit" class="btn btn-default btn-submit">Submit message</button>
							
						</form>
						
						<div id="response"></div>
						
					</section> -->
					
					<!-- ============================================================= SECTION – CONTACT FORM : END ============================================================= -->
					
					
					<!-- ============================================================= SECTION – CONTACTS ============================================================= -->
					
					<section id="contacts" class="inner-top-md inner-bottom-sm">
						
						<h2>Contacts</h2>
						<p>Magnis modipsae voloratati andigen daepeditem quiate re aut labor. <br>Laceaque eictemperum quiae sitiorem rest non restibusaes.</p>
						
						<div class="row">
							<div class="col-sm-6">
								<h3>REEN</h3>
								<ul class="contacts">
									<li><i class="icon-location contact"></i> 84 Street, City, State 24813</li>
									<li><i class="icon-mobile contact"></i> +00 (123) 456 78 90</li>
									<li><a href="#"><i class="icon-mail-1 contact"></i> info@reen.com</a></li>
								</ul><!-- /.contacts -->
							</div><!-- /.col -->
						</div><!-- /.row -->
						
					</section>
					
					<!-- ============================================================= SECTION – CONTACTS : END ============================================================= -->
					
				</div><!-- ./col -->
				
				<div class="col-md-4">
					
					<!-- ============================================================= SECTION – CONTACT NAMES ============================================================= -->
					
					<section id="contact-names" class="light-bg inner-xs inner-left-xs inner-right-xs">
							
						<h3 class="team-headline sidelines text-center"><span>Contact names</span></h3>
						
						<div class="row thumbs gap-md text-center">
							{% for author in authors %}
							<div class="col-sm-6 thumb">
								<figure class="member">
									
									<div class="member-image">
										
										<div class="text-overlay">
											<div class="info">
												<ul class="social">
													<li><a href="{{ author.facebook_url }}" target="_blank"><i class="icon-s-facebook"></i></a></li>
													<li><a href="{{ author.linkedin_url }}" target="_blank"><i class="icon-s-linkedin"></i></a></li> 
													<li><a href="{{ author.twitter_url }}" target="_blank"><i class="icon-s-twitter"></i></a></li>
												</ul><!-- /.social -->
											</div><!-- /.info -->
										</div><!-- /.text-overlay -->
										
										<img src="{{ MEDIA_URL }}{{ author.image }}">
										
									</div><!-- /.member-image -->
									
									<figcaption class="member-details bordered no-top-border">
										<h3>
											{{ author.display_name }} 
											<span>{{ author.title }}</span>
										</h3>
									</figcaption>
									
								</figure>
							</div><!-- /.col -->
							{% if forloop.counter|divisibleby:2 %}
							</div>
							<div class="row thumbs gap-md text-center">
							{% endif %}
							{% endfor %}
						</div><!-- /.row -->
						
					</section>
					
					<!-- ============================================================= SECTION – CONTACT NAMES : END ============================================================= -->
					
				</div><!-- /.col -->
					
			</div><!-- /.row -->
		</div><!-- /.container -->
		
	</main>
	
	<!-- ============================================================= MAIN : END ============================================================= -->
{% endblock content %}

{% block jsextra %}
{% endblock jsextra %}

templates/index.html
{% extends "layout/base.html" %}
{% load static from staticfiles %}

{% block title %}Home{% endblock title %}

{% block cssextra %}
{% endblock cssextra %}

{% block content %}
	<!-- ============================================================= SECTION – HERO ============================================================= -->
			
			<section id="hero">
				<div id="owl-main" class="owl-carousel height-lg owl-inner-nav owl-ui-lg">
					
					<div class="item" style="background-image: url(https://thumbs.dreamstime.com/z/pool-edge-background-wood-pavement-35532516.jpg);">
						<div class="container">
							<div class="caption vertical-center text-center">
								
								<h1 class="fadeInDown-1 navy-bg light-color">Ready to Jump In?</h1>
								<p class="fadeInDown-2 navy-bg light-color">Some stuff about how complicated web design and development projects can be. It's a little bit daunting, but don't worry because we're here and we're awesome.</p>
								<div class="fadeInDown-3">
									<a href="{% url 'contact' %}" class="btn btn-large">Let us help</a>
								</div><!-- /.fadeIn -->
								
							</div><!-- /.caption -->
						</div><!-- /.container -->
					</div><!-- /.item -->
					
					<div class="item" style="background-image: url(http://previews.123rf.com/images/everythingpossible/everythingpossible1301/everythingpossible130100200/17156762-web-designer-working-on-modern-computer-Stock-Photo-web.jpg);">
						<div class="container">
							<div class="caption vertical-center text-right">
								
								<h1 class="fadeInLeft-1 navy-bg light-color">We specialize <br>in <em>really</em> cool stuff</h1>
								<p class="fadeInLeft-2 navy-bg light-color">Here is an image of the kind of really cool stuff we specialize in, as we just mentioned.</p>
								<div class="fadeInLeft-3">
									<a href="{% url 'contact' %}" class="btn btn-large">I like cool stuff</a>
								</div><!-- /.fadeIn -->
								
							</div><!-- /.caption -->
						</div><!-- /.container -->
					</div><!-- /.item -->
					
					<div class="item" style="background-image: url({% static 'images/art/slider03.jpg' %});">
						<div class="container">
							<div class="caption vertical-center text-left">
								
								<h1 class="fadeInRight-1 dark-bg light-color"><span>Let us handle <br>the technology</span></h1>
								<p class="fadeInRight-2 dark-color">Web technologies are complicated, but we know a bunch of stuff about it.</p>
								<div class="fadeInRight-3">
									<a href="{% url 'contact' %}" class="btn btn-large">Oh thank Jesus</a>
								</div><!-- /.fadeIn -->
								
							</div><!-- /.caption -->
						</div><!-- /.container -->
					</div><!-- /.item -->
					
					<div class="item" style="background-image: url({% static 'images/art/slider04.jpg' %});">
						<div class="container">
							<div class="caption vertical-top text-right">
								
								<h1 class="fadeIn-1 dark-bg light-color"><span>Just focus on <br>your business plan</span></h1>
								<p class="fadeIn-2 light-color">Take a break from worrying about the technology and spend <br>your time brainstorming ideas for your next project.</p>
								<div class="fadeIn-3">
									<a href="{% url 'contact' %}" class="btn btn-large">Yes, I business</a>
								</div><!-- /.fadeIn -->
								
							</div><!-- /.caption -->
						</div><!-- /.container -->
					</div><!-- /.item -->
					
					<div class="item" style="background-image: url({% static 'images/art/slider05.jpg' %});">
						<div class="container">
							<div class="caption vertical-top text-center">
								
								<h1 class="fadeInDown-1 light-color">Just relax <br>we've got this shit</h1>
								<p class="fadeInDown-2 medium-color">Some more reassuring stuff about how great we are about handling the treacherous internets</p>
								<div class="fadeInDown-3">
									<a href="{% url 'contact' %}" class="btn btn-large">Take my money</a>
								</div><!-- /.fadeIn -->
								
							</div><!-- /.caption -->
						</div><!-- /.container -->
					</div><!-- /.item -->
					
				</div><!-- /.owl-carousel -->
			</section>
			
			<!-- ============================================================= SECTION – HERO : END ============================================================= -->
			
			
			<!-- ============================================================= SECTION – WHO WE ARE ============================================================= -->
			
			<section id="who-we-are">
				<div class="container inner-top inner-bottom-sm">
					
					<div class="row">
						<div class="col-md-8 col-sm-9 center-block text-center">
							<header>
								<h1>Beautiful. Clean. Responsive.</h1>
								<p>REEN is a high-quality solution for those who want a beautiful website in no time. It's fully responsive and will adapt itself to any mobile device. iPad, iPhone, Android, it doesn't matter. Your content will always looks its absolute best.</p>
							</header>
						</div><!-- /.col -->
					</div><!-- /.row -->
				
					<div class="row inner-top-sm">
						
						<div class="col-md-1">
							<div class="icon pull-right">
								<i class="icon-palette icn"></i>
							</div><!-- /.icon -->
						</div><!-- /.col -->
						
						<div class="col-md-3 inner-bottom-xs">
							<h2>Design</h2>
							<p class="text-small">Magnis modipsae que lib voloratati andigen daepeditem quiate re porem aut labor. Laceaque quiae sitiorem rest non restibusaes maio es dem tumquam core posae volor remped modis volor.</p>
						</div><!-- /.col -->
						
						<div class="col-md-1">
							<div class="icon pull-right">
								<i class="icon-beaker icn"></i>
							</div><!-- /.icon -->
						</div><!-- /.col -->
					
						<div class="col-md-3 inner-bottom-xs">
							<h2>Develop</h2>
							<p class="text-small">Magnis modipsae que lib voloratati andigen daepeditem quiate re porem aut labor. Laceaque quiae sitiorem rest non restibusaes maio es dem tumquam core posae volor remped modis volor.</p>
						</div><!-- /.col -->
						
						<div class="col-md-1">
							<div class="icon pull-right">
								<i class="icon-rocket icn"></i>
							</div><!-- /.icon -->
						</div><!-- /.col -->
					
						<div class="col-md-3 inner-bottom-xs">
							<h2>Deploy</h2>
							<p class="text-small">Magnis modipsae que lib voloratati andigen daepeditem quiate re porem aut labor. Laceaque quiae sitiorem rest non restibusaes maio es dem tumquam core posae volor remped modis volor.</p>
						</div><!-- /.col -->
						
					</div><!-- /.row -->
				
				</div><!-- /.container -->
			</section>
			
			<!-- ============================================================= SECTION – WHO WE ARE : END ============================================================= -->
			
			
			<!-- ============================================================= SECTION – LATEST WORKS ============================================================= -->
		
			<section id="latest-works" class="light-bg">
				<div class="container inner">
					
					<div class="row">
						<div class="col-md-8 col-sm-9 center-block text-center">
							<header>
								<h1>Check out our latest works</h1>
								<p>Magnis modipsae que voloratati andigen daepeditem quiate re porem aut labor.</p>
							</header>
						</div><!-- /.col -->
					</div><!-- /.row -->
				 
					<div class="row">
						{% for project in feature_projects %}
						<div class="col-sm-6 inner-top-sm">
							<figure>
							
								<div class="icon-overlay icn-link">
									<a href="{% url 'projects:detail' project.pk %}"><img src="{{ MEDIA_URL }}{{ project.images.first.image }}" alt=""></a>
								</div><!-- /.icon-overlay -->
								
								<figcaption class="bordered no-top-border">
									<div class="info">
										<h3><a href="{% url 'projects:detail' project.pk %}">{{ project.title }}</a></h3>
										<p>{{ project.types.all|join:", " }}</p>
									</div><!-- /.info -->
								</figcaption>
								
							</figure>
						</div><!-- /.col -->
						{% endfor %}
					</div>

					<div class="row inner-top-sm">
						<div id="owl-latest-works" class="owl-carousel owl-item-gap">
							{% for project in other_projects %}
							<div class="item">
								<a href="{% url 'projects:detail' project.pk %}">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>{{ project.title }}</h4>
												<p>{{ project.types.all|join:", " }}</p>
											</div><!-- /.info -->
										</figcaption>
										<img src="{{ MEDIA_URL }}{{ project.images.first.image }}" alt="{{ project.images.first.name }}">
									</figure>
								</a>
							</div><!-- /.item -->
							{% endfor %}
						</div><!-- /.owl-carousel -->
					</div><!-- /.row -->
					
				</div><!-- /.container -->
			</section>
			
			<!-- ============================================================= SECTION – LATEST WORKS : END ============================================================= -->
			
			
			<!-- ============================================================= SECTION – GET IN TOUCH ============================================================= -->
			
			<section id="get-in-touch">
				<div class="container inner">
					<div class="row">
						<div class="col-md-8 col-sm-9 center-block text-center">
							<header>
								<h1>Want to work with us?</h1>
								<p>Magnis modipsae que voloratati andigen daepeditem quiate re porem aut labor. Laceaque quiae sitiorem rest non restibusaes maio es dem tumquam.</p>
							</header>
							<a href="{% url 'contact' %}" class="btn btn-large">Get in touch</a>
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container -->
			</section>
			
			<!-- ============================================================= SECTION – GET IN TOUCH : END ============================================================= -->
{% endblock content %}

{% block jsextra %}
{% endblock jsextra %}

templates/services.html
{% extends "layout/base.html" %}
{% load static from staticfiles %}

{% block title %}Services{% endblock title %}

{% block cssextra %}
{% endblock cssextra %}

{% block content %}
	<!-- ============================================================= MAIN ============================================================= -->
		
	<main>
		
		<!-- ============================================================= SECTION – HERO ============================================================= -->
	
		<section id="hero" class="light-bg img-bg-bottom img-bg-softer" style="background-image: url({% static 'images/art/slider03.jpg' %});">
			<div class="container inner">
				
				<div class="row">
					<div class="col-md-8 col-sm-9">
						<header>
							<h1>Services</h1>
							<p>Magnis modipsae que voloratati andigen daepeditem quiate aut labor. Laceaque quiae sitiorem rest non restibusaes es dem tumquam.</p>
						</header>
					</div><!-- /.col -->
				</div><!-- ./row -->
				
			</div><!-- /.container -->
		</section>
		
		<!-- ============================================================= SECTION – HERO : END ============================================================= -->
		
		<!-- ============================================================= SECTION – SERVICES ============================================================= -->
		
		<section id="services" class="dark-bg">
			<div class="container inner">
				<div class="row">
					<div class="col-xs-12">
						<div class="tabs tabs-services tabs-circle-top tab-container">
							
							<ul class="etabs text-center">
								<li class="tab"><a href="#tab-1"><div><i class="icon-lamp"></i></div>Strategy</a></li>
								<li class="tab"><a href="#tab-2"><div><i class="icon-flow-tree"></i></div>UX</a></li>
								<li class="tab"><a href="#tab-3"><div><i class="icon-beaker"></i></div>Design</a></li>
								<li class="tab"><a href="#tab-4"><div><i class="icon-code"></i></div>Technology</a></li>
								<li class="tab"><a href="#tab-5"><div><i class="icon-thumbs-up-1"></i></div>Social</a></li>
								<li class="tab"><a href="#tab-6"><div><i class="icon-megaphone-1"></i></div>Marketing</a></li>
							</ul><!-- /.etabs -->
							
							<div class="panel-container">
								
								<div class="tab-content" id="tab-1">
									<div class="row">
										
										<div class="col-md-5 col-md-offset-1 col-sm-6 inner-right-xs">
											<figure><img src="{% static 'images/art/product05.jpg' %}" alt=""></figure>
										</div><!-- /.col -->
										
										<div class="col-md-5 col-sm-6 inner-top-xs inner-left-xs">
											<h3>Strategy</h3>
											<p>Magnis modipsae que lib voloratati andigen daepedor quiate ut reporemni aut labor. Laceaque quiae sitiorem ut restibusaes es tumquam core posae volor remped modis volor. Doloreiur qui commolu ptatemp dolupta orem retibusam emnis et consent accullignis lomnus.</p>
										</div><!-- /.col -->
										
									</div><!-- /.row -->
								</div><!-- /.tab-content -->
								
								<div class="tab-content" id="tab-2">
									<div class="row">
										
										<div class="col-md-5 col-md-push-5 col-md-offset-1 col-sm-6 col-sm-push-6 inner-left-xs">
											<figure><img src="{% static 'images/art/product01.jpg' %}" alt=""></figure>
										</div><!-- /.col -->
										
										<div class="col-md-5 col-md-pull-5 col-sm-6 col-sm-pull-6 inner-top-xs inner-right-xs">
											<h3>User Experience</h3>
											<p>Magnis modipsae que lib voloratati andigen daepedor quiate ut reporemni aut labor. Laceaque quiae sitiorem ut restibusaes es tumquam core posae volor remped modis volor. Doloreiur qui commolu ptatemp dolupta orem retibusam emnis et consent accullignis lomnus.</p>
										</div><!-- /.col -->
										
									</div><!-- /.row -->
								</div><!-- /.tab-content -->
								
								<div class="tab-content" id="tab-3">
									<div class="row">
										
										<div class="col-md-4 col-md-push-3 col-md-offset-1 col-sm-6 inner-left-xs inner-right-xs">
											<figure><img src="{% static 'images/art/product06.jpg' %}" alt=""></figure>
										</div><!-- /.col -->
										
										<div class="col-md-3 col-md-pull-4 col-sm-6 inner-top-xs">
											<h3>Design</h3>
											<p>Magnis modipsae lib voloratati andigen daepedor quiate aut labor. Laceaque quiae sitiorem resti est lore tumquam core posae volor uso remped modis volor. Doloreiur qui commolu ptatemp dolupta orem retibusam emnis et consent it accullignis orum lomnus.</p>
										</div><!-- /.col -->
										
										<div class="col-md-3 col-sm-6 inner-top-xs">
											<h3>User interface</h3>
											<p>Magnis modipsae lib voloratati andigen daepedor quiate aut labor. Laceaque quiae sitiorem resti est lore tumquam core posae volor uso remped modis volor. Doloreiur qui commolu ptatemp dolupta orem retibusam emnis et consent it accullignis orum lomnus.</p>
										</div><!-- /.col -->
										
									</div><!-- /.row -->
								</div><!-- /.tab-content -->
								
								<div class="tab-content" id="tab-4">
									<div class="row">
										<div class="col-md-8 col-sm-9 center-block text-center">
											<h3>Technology</h3>
											<p>Magnis modipsae que lib voloratati andigen daepeditem quiate ut reporemni aut labor. Laceaque quiae sitiorem rest non restibusaes es tumquam core posae volor remped modis volor. Doloreiur qui commolu ptatemp dolupta oreprerum tibusam emnis et consent accullignis.</p>
										</div><!-- /.col -->
									</div><!-- /.row -->
								</div><!-- /.tab-content -->
								
								<div class="tab-content" id="tab-5">
									
									<div class="row">
										<div class="col-md-5 col-sm-6 col-xs-8 center-block text-center">
											<figure><img src="{% static 'images/art/product03.jpg' %}" alt=""></figure>
										</div><!-- /.col -->
									</div><!-- /.row -->
									
									<div class="row">
										<div class="col-sm-8 center-block text-center inner-top-xs">
											<h3>Social</h3>
											<p>Magnis modipsae que lib voloratati andigen daepedor quiate ut reporemni aut labor. Laceaque sitiorem ut restibusaes es tumquam core posae volor remped modis volor. Doloreiur qui commolu ptatemp dolupta orem retibusam emnis et consent accullignis lomnus.</p>
										</div><!-- /.col -->
									</div><!-- /.row -->
									
								</div><!-- /.tab-content -->
								
								<div class="tab-content" id="tab-6">
									
									<div class="row">
										<div class="col-sm-8 center-block text-center">
											<h3>Marketing</h3>
											<p>Magnis modipsae que lib voloratati andigen daepedor quiate ut reporemni aut labor. Laceaque sitiorem ut restibusaes es tumquam core posae volor remped modis volor. Doloreiur qui commolu ptatemp dolupta orem retibusam emnis et consent accullignis lomnus.</p>
										</div><!-- /.col -->
									</div><!-- /.row -->
									
									<div class="row">
										<div class="col-md-5 col-sm-6 col-xs-8 inner-top-xs center-block text-center">
											<figure><img src="{% static 'images/art/humans01.jpg' %}" alt=""></figure>
										</div><!-- /.col -->
									</div><!-- /.row -->
									
								</div><!-- /.tab-content -->
								 
							</div><!-- /.panel-container -->
							 
						</div><!-- /.tabs -->
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</section>
		
		<!-- ============================================================= SECTION – SERVICES : END ============================================================= -->
		
		
		<!-- ============================================================= SECTION – CLIENTS ============================================================= -->
	
		<section id="clients">
			<div class="container inner">
				
				<div class="row">
					<div class="col-md-8 col-sm-9 center-block text-center">
						<header>
							<h1>Technology</h1>
							<p>Here are some logos of stuff that we do things with.</p>
						</header>
					</div><!-- /.col -->
				</div><!-- /.row -->
				
				<div class="row inner-top-sm">
					<div class="col-sm-12">
						<div id="owl-clients" class="owl-carousel owl-outer-nav">
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>Django Framework</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/django-logo-positive.png' %}" alt="Django Framework">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>Ionic Framework</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/ionic_logo.png' %}" alt="Ionic Framework">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>Flask</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/flask-logo.png' %}" alt="Flask">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>AngularJS</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/angular-logo.png' %}" alt="AngularJS">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>MySQL</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/mysql-logo.jpg' %}" alt="MySQL">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>Sass</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/sass-logo.png' %}" alt="Sass">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>Git Version Control</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/git-logo.png' %}" alt="Git">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>WordPress CMS</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/wordpress-logo.png' %}" alt="WordPress CMS">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>Laravel Framework</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/laravel-logo.png' %}" alt="Laravel Framework">
									</figure>
							</div><!-- /.item -->
							
							<div class="item">
									<figure>
										<figcaption class="text-overlay">
											<div class="info">
												<h4>Twitter Bootstrap</h4>
											</div><!-- /.info -->
										</figcaption>
										<img src="{% static 'images/logos/bootstrap-logo.png' %}" alt="Twitter Bootstrap">
									</figure>
							</div><!-- /.item -->
							
						</div><!-- /.owl-carousel -->
					</div><!-- /.col -->
				</div><!-- /.row -->
				
			</div><!-- /.container -->
		</section>
		
		<!-- ============================================================= SECTION – CLIENTS : END ============================================================= -->
		
		
		<!-- ============================================================= SECTION – GET IN TOUCH ============================================================= -->
		
		<section id="get-in-touch" class="light-bg">
			<div class="container inner-sm">
				<div class="row">
					<div class="col-sm-10 center-block text-center">
						<h1 class="single-block">Want to work with us? <a href="{% url 'contact' %}" class="btn btn-large">Get in touch</a></h1>
					</div><!-- /.col -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</section>
		
		<!-- ============================================================= SECTION – GET IN TOUCH : END ============================================================= -->
		
	</main>
	
	<!-- ============================================================= MAIN : END ============================================================= -->
{% endblock content %}

{% block jsextra %}
{% endblock jsextra %}